[project]
name = "ansible-chatbot-stack"
version = "0.1.0"
description = "Ansible Lightspeed Intelligent Assistant (ALIA)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu~=1.11",
    "lightspeed-stack-providers==0.1.17",
    "mcp~=1.9.4",
    "sentence-transformers>=5.0.0",
    "dumb-init>=1.2.5.post1",
    "litellm>=1.79.0",
]

[dependency-groups]
dev = [
    "cachetools>=6.1.0",
    "kubernetes>=33.1.0",
    "locust>=2.39.1",
]
